sudo: false
language: node_js
node_js:
  - '10.13.0'
branches:
  only:
  - master
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master